repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: uv run pylint
        language: system
        types: [python]
        require_serial: true
        exclude: ^src/rag/rag\.py$

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black